{% set name = "system-slash" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b4172ea0d8cb8d573b3fdc254fe21c7b117324c249dd05d4c4f91fdbc4254f33

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - SystemSlash

about:
  home: "https://github.com/sujitmandal/system-slash"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "It will find operating system and then generate slash as per system required."
  doc_url: https://sujitmandal.github.io/system-slash/
  dev_url: https://github.com/sujitmandal/system-slash

extra:
  recipe-maintainers:
    - sujitmandal
